CXX = g++

LIBCOMMON = libcommon.dll
LIBLAYOUT = liblayout.dll
LIBADDITIONAL = libadditional.dll

WXFBDIR = ../../..
WXWINDIR = $(WXFBDIR)/libs/wxWidgets-2.6.0_dll

# LDFLAGS = -L. -LC:/wx-2.5.4_compiled_as_dll_release/lib -mthreads -mwindows
#EXTRALIBS =  -mthreads -lrpcrt4 -loleaut32 -lole32 -luuid -lodbc32 -lole32 -loleaut32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lcomdlg32 -lctl3d32 -ladvapi32 -lwsock32 -lgdi32
# -mthreads -Wl,--subsystem,windows -mwindows -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32_@@_

DEBUG = -g
CXXINCS = -I$(WXWINDIR)/include -I$(WXFBDIR)/libs/tinyxml -I../..
CXXFLAGS = -Wall -g -O0 -mthreads -DHAVE_W32API_H -D__WXMSW__ -DWXUSINGDLL -DNOPCH -Wno-ctor-dtor-privacy -DNO_GCC_PRAGMA -DTIXML_USE_STL -D__WXFB_DEBUG__ $(DEBUG)

LDFLAGS = -mwindows -mthreads -Wl,--subsystem,windows -mwindows -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32 -lstdc++
LIBS = -lwxmsw26 -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregex -lwxexpat -lwxmsw26_stc -ltinyxml -L$(WXFBDIR)/libs/tinyxml -L$(WXWINDIR)/lib 

all: $(LIBCOMMON) $(LIBLAYOUT) $(LIBADDITIONAL)
	cp *.dll $(WXFBDIR)/bin/xml

$(LIBCOMMON): common.o xrcconv.o
	$(CXX) -L. -shared -o $(LIBCOMMON) common.o xrcconv.o $(LDFLAGS) $(LIBS)
	strip $(LIBCOMMON)

common.o: common.cpp
	$(CXX) -c $(CXXFLAGS) $(CXXINCS) -o common.o common.cpp

$(LIBLAYOUT): layout.o xrcconv.o
	$(CXX) -L. -shared -o $(LIBLAYOUT) layout.o xrcconv.o $(LDFLAGS) $(LIBS)
	strip $(LIBLAYOUT)

layout.o: layout.cpp xrcconv.o
	$(CXX) -c $(CXXFLAGS) $(CXXINCS) -o layout.o layout.cpp
	
xrcconv.o: $(WXFBDIR)/src/utils/xrcconv.cpp
	$(CXX) -c $(CXXFLAGS) $(CXXINCS) -o xrcconv.o $(WXFBDIR)/src/utils/xrcconv.cpp

$(LIBADDITIONAL): additional.o xrcconv.o
	$(CXX) -L. -shared -o $(LIBADDITIONAL) additional.o xrcconv.o $(LDFLAGS) $(LIBS)
	strip $(LIBADDITIONAL)

additional.o: additional.cpp
	$(CXX) -c $(CXXFLAGS) $(CXXINCS) -o additional.o additional.cpp
	

clean:
	rm *.o *.dll
